variable "allocated_storage" {}
variable "name" {}
variable "engine" {}
variable "engine_version" {}
variable "instance_class" {}
variable "subnet_ids" {}
variable "snapshot_arn" {}
variable "cidr_block" {}
variable "vpc_id" {}
